name: Codecov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Run tests and collect coverage
        run: npm run test
      - name: Upload coverage to Codecov (demo)
        uses: ./
        with:
          token: ${{ secrets.CODECOV_TOKEN }} 
          files: ./coverage/calculator/coverage-final.json,./coverage/coverage-test/coverage-final.json
          file: ./coverage/coverage-final.json
          flags: unittests
          name: codecov-umbrella
          verbose: true
      - name: Upload coverage to Codecov (script)
        uses: ./
        with:
          files: ./coverage/script/coverage-final.json
          flags: script
          name: codecov-script
