name: Deploy to Cloud Run

on:
  workflow_run:
    workflows: ["Build and Publish Docker Image"]
    branches: ['test']
    types:
      - completed

# General Environments variables
env:
  # Google Cloud Env
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_ZONE: ${{ secrets.GCP_ZONE }}

  # Image Env
  IMAGE: data-corner
  TAG: staging

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    # Setup gcloud CLI
    - name: Set up Cloud credentials
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name : Deploy Cloud Run
      run : |-
        gcloud run deploy $IMAGE \
        --image eu.gcr.io/$GCP_PROJECT_ID/$IMAGE:$TAG \
        --platform managed \
        --region $GCP_ZONE \
        --memory 1024Mi \
        --labels=type=$TAG #\
